---
  ## Copiar archivo desde el servidor Tower al servidor destino
  ## Autor: Jorge Zavala Navarro

- name: COPIAR UN ARCHIVO DESDE EL SERVIDOR DE TOWER AL SERVIDOR DESTINO
  hosts: all
  gather_facts: yes
  
  vars:
          archivo_origen: /home/jzavala74mz/Uploads/Apr2006_MDX1_x86_Archive.cab
          ruta_destino: /home/jzavala74mz/Recepts

  tasks:
          - name: Crear la carpeta destino
            file:
                    path: '{{ ruta_destino }}'
                    state: directory
                    mode: '0755'

          - name: Transfiriendo archivo de instalación
            command: 'expect {{ path_repogit_dir }}/ScriptCopyinstalador.sh'


